### ISSUE TITLE
"host" parameter misleading

### ISSUE THREAD

**Issue by Pistahh** [mseri/xapirpc-rs#8]
as it requires not a hostname/ip to be provided but the base url (http://...) to access the host.

**Comment by mseri** [comment]
Partially fixed in 0.6.0. Now it's enough to give the host name. It defaults to `https` so you may get ssl errors for invalid certificates, I have an addiitional commit, pending on the release of the new `reqwest`, to also disable `ssl` checks at client level. I decided not to use `http`/`https` depending on the flag in the hope of a fast release (the change is pending in the upstream libraries since the end of december and it's slowly being released)
